[package]
name = "pwgen-vs-words"
description = "Generate passwords with pgwen and check if generated passwords are in english dictionary"
version = "0.0.1"
authors = ["Đorđe Zeljić <zeljic@gmail.com>"]

[dependencies]
clap = "2.30.0"
